mongoexport --db netmeds --collection Acne --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Acne.json
mongoexport --db netmeds --collection Adhd --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Adhd.json
mongoexport --db netmeds --collection AlcoholAddiction --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/AlcoholAddictiondb.json
mongoexport --db netmeds --collection Allergies --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Allergies.json
mongoexport --db netmeds --collection Alzheimer --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Alzheimer.json
mongoexport --db netmeds --collection Amoebiasis --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Amoebiasis.json
mongoexport --db netmeds --collection Anaemia --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Anaemia.json
mongoexport --db netmeds --collection AnaesthesiaGeneral --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/AnaesthesiaGeneral.json
mongoexport --db netmeds --collection AnaesthesiaLocal --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/AnaesthesiaLocal.json
mongoexport --db netmeds --collection Angian --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Angian.json
mongoexport --db netmeds --collection Anxiety --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Anxiety.json
mongoexport --db netmeds --collection Appetite --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Appetite.json
mongoexport --db netmeds --collection Arrhythmiasis --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Arrhythmiasis.json
mongoexport --db netmeds --collection Arthritis --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Arthritis.json
mongoexport --db netmeds --collection Asthma/Copd --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/AsthmaCopd.json
mongoexport --db netmeds --collection AutoImmuneDisease --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/AutoImmuneDisease.json
mongoexport --db netmeds --collection AyurvedicMedicine --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/AyurvedicMedicine.json
mongoexport --db netmeds --collection BladderAndProstrateDisorders --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/BladderAndProstrateDisorders.json
mongoexport --db netmeds --collection BleedingDisorders --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/BleedingDisorders.json
mongoexport --db netmeds --collection BloodClot --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/BloodClot.json
mongoexport --db netmeds --collection BoneMetabolism --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/BoneMetabolism.json
mongoexport --db netmeds --collection Cancer/Oncology --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/CancerOncology.json
mongoexport --db netmeds --collection Cholelithiasis/GallStones --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/CholelithiasisGallStones.json
mongoexport --db netmeds --collection Cleanser --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Cleanser.json
mongoexport --db netmeds --collection Constipation --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Constipation.json
mongoexport --db netmeds --collection Contraception --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Contraception.json
mongoexport --db netmeds --collection 'Cough&Cold' --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/'Cough&Cold.json'
mongoexport --db netmeds --collection Dandruff --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Dandruff.json
mongoexport --db netmeds --collection Depression --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Depression.json
mongoexport --db netmeds --collection Diabetes --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Diabetes.json
mongoexport --db netmeds --collection Diarrhoea --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Diarrhoea.json
mongoexport --db netmeds --collection Digestion --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Digestion.json
mongoexport --db netmeds --collection DryEye --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/DryEye.json
mongoexport --db netmeds --collection DrySkin --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/DrySkin.json
mongoexport --db netmeds --collection EarConditions --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/EarConditions.json
mongoexport --db netmeds --collection Epilepsy/Convulsion --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/EpilepsyConvulsion.json
mongoexport --db netmeds --collection Fever --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Fever.json
mongoexport --db netmeds --collection Fungal --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Fungal.json
mongoexport --db netmeds --collection GastroIntestinalMotilityDisorders --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/GastroIntestinalMotilityDisorders.json
mongoexport --db netmeds --collection Generals --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Generals.json
mongoexport --db netmeds --collection Glaucoma --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Glaucoma.json
mongoexport --db netmeds --collection Gout --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Gout.json
mongoexport --db netmeds --collection Haematopoiesis --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Haematopoiesis.json
mongoexport --db netmeds --collection Haemorrhoid --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Haemorrhoid.json
mongoexport --db netmeds --collection HairLoss --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/HairLoss.json
mongoexport --db netmeds --collection HeartFailure --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/HeartFailure.json
mongoexport --db netmeds --collection HepatitisBInfection --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/HepatitisBInfection.json
mongoexport --db netmeds --collection HighCholestrol --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/HighCholestrol.json
mongoexport --db netmeds --collection HormonalTherapy --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/HormonalTherapy.json
mongoexport --db netmeds --collection HyperPigmentation --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/HyperPigmentation.json
mongoexport --db netmeds --collection Hypertension --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Hypertension.json
mongoexport --db netmeds --collection Hyperthyroidsm --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Hyperthyroidsm.json
mongoexport --db netmeds --collection Hypnosis --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Hypnosis.json
mongoexport --db netmeds --collection Hypothyroidism --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Hypothyroidism.json
mongoexport --db netmeds --collection Impotence/ErectileDysfunction --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/ImpotenceErectileDysfunction.json
mongoexport --db netmeds --collection Infection --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Infection.json
mongoexport --db netmeds --collection KidneyDisease/Stones --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/KidneyDiseaseStones.json
mongoexport --db netmeds --collection Leprosy --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Leprosy.json
mongoexport --db netmeds --collection LiverDisease --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/LiverDisease.json
mongoexport --db netmeds --collection Ulcer/Reflux/Flatulence --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/UlcerRefluxFlatulence.json
mongoexport --db netmeds --collection UlcerativeColitis/BowelInflamatoryDisease --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/UlcerativeColitisBowelInflamatoryDisease.json
mongoexport --db netmeds --collection UrinaryRetention --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/UrinaryRetention.json
mongoexport --db netmeds --collection UterusConditions --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/UterusConditions.json
mongoexport --db netmeds --collection Vaccines --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Vaccines.json
mongoexport --db netmeds --collection VaginalConditions --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/VaginalConditions.json
mongoexport --db netmeds --collection VaricoseVeins --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/VaricoseVeins.json
mongoexport --db netmeds --collection Vertigo --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Vertigo.json
mongoexport --db netmeds --collection Viral --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Viral.json
mongoexport --db netmeds --collection Vomitting/Emesis --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/VomittingEmesis.json
mongoexport --db netmeds --collection Warts/Calluses/OtherSkinLesion --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/WartsCallusesOtherSkinLesion.json
mongoexport --db netmeds --collection Wound --out /Users/daaniyaal/Desktop/Medicento/Medicine\ Database/Wound.json
